<?php
$label=function(string $catalog,mixed $id)use($catalogs):string{foreach($catalogs[$catalog]??[] as $item)if((string)$item['id']===(string)$id)return $item['label'];return 'Registro histórico #'.$id;};
$state=$document['estado_registro']; $workflowAvailable=false; $options=has_role('ADMIN','SUPERVISOR')?match($state){'BORRADOR'=>['VALIDADO'=>'Validar'],'VALIDADO'=>['OBSERVADO'=>'Observar','PUBLICADO'=>'Publicar'],'OBSERVADO'=>['BORRADOR'=>'Devolver a borrador'],'PUBLICADO'=>['ANULADO'=>'Anular'],default=>[]}:[];
?>
<link rel="stylesheet" href="<?=url('/assets/css/documentos-michel.css')?>">
<section class="module-header"><div><div class="page-eyebrow">DETALLE DEL DOCUMENTO</div><h1 class="page-title"><?=e($document['numero'])?></h1><p class="page-subtitle"><?=e($label('tipo_documento_id',$document['tipo_documento_id']))?> · <?=e($document['fecha'])?></p></div><a class="btn btn-outline-primary" href="<?=url('/documentos')?>">Volver al listado</a></section>
<section class="card mb-3"><div class="card-body p-4"><div class="d-flex flex-wrap justify-content-between gap-2 mb-3"><h2 class="h5">Datos generales</h2><span class="badge-status status-<?=e(strtolower($state))?>"><?=e($state)?></span></div><dl class="row"><div class="col-12 col-md-4"><dt>Cliente</dt><dd><?=e($label('cliente_id',$document['cliente_id']))?></dd></div><div class="col-12 col-md-4"><dt>Vendedor</dt><dd><?=e($label('vendedor_id',$document['vendedor_id']))?></dd></div><div class="col-12 col-md-4"><dt>Sucursal</dt><dd><?=e($label('sucursal_id',$document['sucursal_id']))?></dd></div></dl><?php if($document['observation_reason']??null):?><div class="alert alert-warning"><strong>Observación:</strong> <?=e($document['observation_reason'])?></div><?php endif;?><?php if($document['cancellation_reason']??null):?><div class="alert alert-secondary"><strong>Anulación:</strong> <?=e($document['cancellation_reason'])?></div><?php endif;?></div></section>
<section class="card mb-3"><div class="card-body p-4"><h2 class="h5">Productos · <?=count($details)?> líneas</h2><div class="table-responsive"><table class="table align-middle"><thead><tr><th>Producto</th><th>Unidad</th><th>Cantidad</th><th>Valor unitario</th></tr></thead><tbody><?php foreach($details as $line):?><tr><td><?=e($label('producto_id',$line['producto_id']))?></td><td><?=e($label('unidad_id',$line['unidad_id']))?></td><td><?=e($line['cantidad'])?></td><td><?=e($line['valor_unitario'])?></td></tr><?php endforeach;?></tbody></table></div></div></section>
<section class="card"><div class="card-body d-flex flex-wrap align-items-center gap-2"><?php if($state==='BORRADOR'&&has_role('ADMIN','DIGITADOR')):?><a class="btn btn-primary" href="<?=url('/documentos/editar?id='.$document['id'])?>">Editar borrador</a><?php else:?><span class="text-muted">Consulta de solo lectura.</span><?php endif;?><?php foreach($options as $target=>$text):?><button type="button" class="btn btn-outline-primary" <?=!$workflowAvailable?'disabled':''?> data-workflow-target="<?=e($target)?>" data-workflow-label="<?=e($text)?>"><?=e($text)?></button><?php endforeach;?></div></section>
<p class="text-muted mt-3">Las acciones de revisión estarán disponibles cuando se integre el servicio de validación del equipo.</p>
<dialog class="doc-dialog" aria-labelledby="workflow-title" data-workflow-dialog><form method="post" action="<?=url('/documentos/estado')?>"><?=csrf_field()?><input type="hidden" name="id" value="<?=e($document['id'])?>"><input type="hidden" name="version" value="<?=e($document['version'])?>"><input type="hidden" name="status" data-workflow-state><h2 class="h4" id="workflow-title">Confirmar acción</h2><p>La acción se aplicará al documento <?=e($document['numero'])?>.</p><div data-reason-wrap><label class="form-label" for="workflow-reason">Motivo</label><textarea id="workflow-reason" class="form-control" name="reason" maxlength="500" rows="3"></textarea></div><div class="d-flex justify-content-end gap-2 mt-3"><button class="btn btn-outline-primary" type="button" data-close-dialog>Cancelar</button><button class="btn btn-primary" type="submit">Confirmar</button></div></form></dialog>
<script src="<?=url('/assets/js/documentos-michel.js')?>" defer></script>
